In [9]:
import pandas as pd
import statsmodels.api as sm
import numpy as np

In [27]:
fff = pd.read_excel('Desktop/IC/Term 1/IPM/data.xls', index_col=0)
fff.head()

,Mkt (vwretd),SMB,HML,Risk-Free,CAP1RET,CAP2RET,CAP3RET,CAP4RET,CAP5RET,CAP6RET,CAP7RET,CAP8RET,CAP9RET,CAP10RET
Month,,,,,,,,,,,,,,
19900131,-0.07360,-0.0123,0.0085,0.0057,-0.03475,-0.05350,-0.05782,-0.03945,-0.06130,-0.06730,-0.08662,-0.06200,-0.07023,-0.06761
19900228,0.00772,0.0095,0.0049,0.0057,0.00352,0.02473,-0.01010,0.00152,0.01538,0.01524,0.01654,0.01692,0.01287,0.01323
19900330,0.01713,0.0142,-0.0287,0.0064,0.01754,0.00024,0.02823,0.01685,0.01706,0.02261,0.03669,0.01710,0.02406,0.02363
19900430,-0.03441,-0.0042,-0.0249,0.0069,-0.03397,-0.02799,-0.03809,-0.04224,-0.03837,-0.03685,-0.04318,-0.04527,-0.04400,-0.02144
19900531,0.08157,-0.0275,-0.0380,0.0068,-0.00653,0.01307,0.03176,0.03126,0.04496,0.06107,0.07091,0.07492,0.08316,0.09363

In [28]:
# excess returns
index = 0
for index in range(4, 14):
    fff[f'Excess_{index-3}'] = fff.iloc[:, index]-fff['Risk-Free']
fff.head()

,Mkt (vwretd),SMB,HML,Risk-Free,CAP1RET,CAP2RET,CAP3RET,CAP4RET,CAP5RET,CAP6RET,...,Excess_1,Excess_2,Excess_3,Excess_4,Excess_5,Excess_6,Excess_7,Excess_8,Excess_9,Excess_10
Month,,,,,,,,,,,,,,,,,,,,,
19900131,-0.07360,-0.0123,0.0085,0.0057,-0.03475,-0.05350,-0.05782,-0.03945,-0.06130,-0.06730,...,-0.04045,-0.05920,-0.06352,-0.04515,-0.06700,-0.07300,-0.09232,-0.06770,-0.07593,-0.07331
19900228,0.00772,0.0095,0.0049,0.0057,0.00352,0.02473,-0.01010,0.00152,0.01538,0.01524,...,-0.00218,0.01903,-0.01580,-0.00418,0.00968,0.00954,0.01084,0.01122,0.00717,0.00753
19900330,0.01713,0.0142,-0.0287,0.0064,0.01754,0.00024,0.02823,0.01685,0.01706,0.02261,...,0.01114,-0.00616,0.02183,0.01045,0.01066,0.01621,0.03029,0.01070,0.01766,0.01723
19900430,-0.03441,-0.0042,-0.0249,0.0069,-0.03397,-0.02799,-0.03809,-0.04224,-0.03837,-0.03685,...,-0.04087,-0.03489,-0.04499,-0.04914,-0.04527,-0.04375,-0.05008,-0.05217,-0.05090,-0.02834
19900531,0.08157,-0.0275,-0.0380,0.0068,-0.00653,0.01307,0.03176,0.03126,0.04496,0.06107,...,-0.01333,0.00627,0.02496,0.02446,0.03816,0.05427,0.06411,0.06812,0.07636,0.08683

In [114]:
X = sm.add_constant(fff.loc["19900131":"20021231", ['Mkt (vwretd)', 'SMB', 'HML']])
model = sm.OLS(fff.loc["19900131":"20021231", ['Excess_1']], X)
results = model.fit()
print(results.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:               Excess_1   R-squared:                       0.445
Model:                            OLS   Adj. R-squared:                  0.434
Method:                 Least Squares   F-statistic:                     40.69
Date:                Mon, 30 Oct 2023   Prob (F-statistic):           2.32e-19
Time:                        09:29:04   Log-Likelihood:                 240.85
No. Observations:                 156   AIC:                            -473.7
Df Residuals:                     152   BIC:                            -461.5
Df Model:                           3
Covariance Type:            nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
const            0.0053      0.004      1.236      0.218      -0.003       0.014
Mkt (vwretd)     0.7236      0.114      6.337      0.000       0.498       0.949
SMB              1.0982      0.123      8.936      0.000       0.855       1.341
HML              0.2454      0.137      1.790      0.075      -0.025       0.516
==============================================================================
Omnibus:                       99.269   Durbin-Watson:                   2.184
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              710.172
Skew:                           2.256   Prob(JB):                    6.14e-155
Kurtosis:                      12.428   Cond. No.                         40.3
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [133]:
beta_mkt = pd.Series(name='beta_mkt')
beta_smb = pd.Series(name='beta_smb')
beta_hml = pd.Series(name='beta_hml')

for index in range(1, 11):
    # Perform the OLS regression
    model = sm.OLS(fff[f'Excess_{index}'], X)
    results = model.fit()
    
    # Collect the estimated coefficients
    beta_mkt.loc[f'CAP{index}RET'] = results.params[1]
    beta_smb.loc[f'CAP{index}RET'] = results.params[2]
    beta_hml.loc[f'CAP{index}RET'] = results.params[3]

/var/folders/j1/b2vqks5s25l2gx6m79t45md80000gn/T/ipykernel_54904/1339552869.py:1: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  beta_mkt = pd.Series(name='beta_mkt')
/var/folders/j1/b2vqks5s25l2gx6m79t45md80000gn/T/ipykernel_54904/1339552869.py:2: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  beta_smb = pd.Series(name='beta_smb')
/var/folders/j1/b2vqks5s25l2gx6m79t45md80000gn/T/ipykernel_54904/1339552869.py:3: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  beta_hml = pd.Series(name='beta_hml')

In [134]:
beta_mkt

CAP1RET     0.723593
CAP2RET     0.852669
CAP3RET     0.795218
CAP4RET     0.808779
CAP5RET     0.875772
CAP6RET     0.962221
CAP7RET     1.063455
CAP8RET     1.035666
CAP9RET     1.117196
CAP10RET    0.983199
Name: beta_mkt, dtype: float64

In [74]:
mpr = pd.read_excel('Desktop/IC/Term 1/IPM/mpr.xls', index_col=0)
mpr.head()

,CAP1RET,CAP2RET,CAP3RET,CAP4RET,CAP5RET,CAP6RET,CAP7RET,CAP8RET,CAP9RET,CAP10RET
Month,,,,,,,,,,
20030131,0.04405,0.02517,0.00885,-0.00467,-0.01386,-0.01943,-0.01577,-0.02960,-0.01999,-0.02723
20030228,-0.04424,-0.01130,-0.01644,-0.01061,-0.02075,-0.01905,-0.03161,-0.02255,-0.01810,-0.02186
20030331,-0.00442,0.00399,0.00246,0.00194,0.00815,0.01482,0.00988,0.01239,0.00747,0.01268
20030430,0.05249,0.05835,0.06615,0.07263,0.08318,0.07991,0.08679,0.09043,0.06759,0.08134
20030530,0.11811,0.09060,0.07257,0.07928,0.08237,0.08497,0.09357,0.08299,0.08838,0.04909

In [109]:
returnex_avg = mpr.iloc[:, 0:10].mean()
returnex_avg

CAP1RET     0.040678
CAP2RET     0.038543
CAP3RET     0.032618
CAP4RET     0.034008
CAP5RET     0.034566
CAP6RET     0.030280
CAP7RET     0.031435
CAP8RET     0.029854
CAP9RET     0.027803
CAP10RET    0.020101
dtype: float64

In [138]:
X1 = pd.concat([beta_mkt, beta_smb, beta_hml], axis=1)
X1 = sm.add_constant(X1, prepend=True)
#X1 = sm.add_constant(pd.concat([beta_mkt, beta_smb, beta_hml], axis=1))

In [139]:
model = sm.OLS(returnex_avg, X1)
results = model.fit()
print(results.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                      y   R-squared:                       0.933
Model:                            OLS   Adj. R-squared:                  0.899
Method:                 Least Squares   F-statistic:                     27.85
Date:                Mon, 30 Oct 2023   Prob (F-statistic):           0.000641
Time:                        09:40:17   Log-Likelihood:                 51.461
No. Observations:                  10   AIC:                            -94.92
Df Residuals:                       6   BIC:                            -93.71
Df Model:                           3
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.0191      0.010      1.914      0.104      -0.005       0.043
beta_mkt       0.0034      0.010      0.342      0.744      -0.021       0.027
beta_smb       0.0187      0.005      4.081      0.006       0.007       0.030
beta_hml      -0.0046      0.008     -0.617      0.560      -0.023       0.014
==============================================================================
Omnibus:                        1.046   Durbin-Watson:                   2.546
Prob(Omnibus):                  0.593   Jarque-Bera (JB):                0.612
Skew:                          -0.555   Prob(JB):                        0.736
Kurtosis:                       2.515   Cond. No.                         41.5
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

/Users/mac/anaconda3/lib/python3.10/site-packages/scipy/stats/_stats_py.py:1736: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=10
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "